### ISSUE TITLE
怎么引入自己的敏感词库

### ISSUE THREAD

**Issue by wanglulei** [houbb/sensitive-word#10]
在项目resources 添加sensitive_word_deny.txt后无法生效

**Comment by houbb** [comment]
也可以试一下 [动态加载](https://github.com/houbb/sensitive-word/#%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD)，文档有。
如果有其他问题，可继续沟通。

**Comment by wanglulei** [comment]
我只要实现这个接口返会就可以了么？还是我实现完还需要自己去过滤。

**Comment by wanglulei** [comment]
如果，我想再你原有的词库中增加相关自己定义的词库这个动态加载可以实现么

**Comment by houbb** [comment]
可以实现，我补充了一下文档。

[自定义配置](https://github.com/houbb/sensitive-word#%E5%90%8C%E6%97%B6%E9%85%8D%E7%BD%AE%E5%A4%9A%E4%B8%AA)

看完文档还不清楚的话，可以参考下测试类：

[SensitiveWordBsDefineTest.java](https://github.com/houbb/sensitive-word/blob/master/src/test/java/com/github/houbb/sensitive/word/define/SensitiveWordBsDefineTest.java)

**Comment by wanglulei** [comment]
好的，感谢。可以了。

**Comment by wanglulei** [comment]
您好，想请教一下，动态自定义实现那个吗，是必须要init初始化一下么？可以在原由基础上add么，如果每次调用init又很耗时，只初始化一次init如果我应用要增加的话，又要重新部署应用。

**Comment by houbb** [comment]
你可以定义一个内部变量，应用启动时初始化对象a，如果需要动态修改时，保持继续使用a，初始化新的对象b，初始化完成后，将a更新为b即可。


不需要重启



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanglulei ***@***.***&gt;
发送时间: 2021年7月14日 10:50
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[houbb/sensitive-word] 怎么引入自己的敏感词库 (#10)





 
您好，想请教一下，动态自定义实现那个吗，是必须要init初始化一下么？可以在原由基础上add么，如果每次调用init又很耗时，只初始化一次init如果我应用要增加的话，又要重新部署应用。

**Comment by wanglulei** [comment]
方便加个联系方式，请教一下么？

**Comment by houbb** [comment]
可以关注下我的公众号：老马啸西风。

我想了下，后期可以新增一个 add/remove 的方法，用来更新词库。
不过最近比较忙……

**Comment by wanglulei** [comment]
好的

**Comment by houbb** [comment]
v0.0.15 版本做了下调整，你看下 [spring 整合](https://github.com/houbb/sensitive-word#spring-%E6%95%B4%E5%90%88)。

修改词库后，自定义的 IWordDeny 从数据库读取数据。SensitiveBs.init()  方法会重新加载一下 IWordDeny 获取新的数据，重新构建词库。
