### ISSUE TITLE
不同的敏感词指定不同的替换词

### ISSUE THREAD

**Issue by nakeiven** [houbb/sensitive-word#13]
不同的敏感词指定不通的替换词，有这样的配置或 api吗？

**Comment by houbb** [comment]
暂时没，都是统一的。
可否说一下应用场景？
如果已经知道敏感词要替换的内容，那可以直接先做一下 replace 替换。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nakeiven ***@***.***&gt;
发送时间: 2022年1月11日 11:36
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 不同的敏感词指定不通的替换词 (Issue #13)





 
不同的敏感词指定不通的替换词，有这样的配置或 api吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nakeiven** [comment]
用同义词替代，比如 游戏 用 电子竞技替代

**Comment by houbb** [comment]
V0.2.0 已支持此特性：[自定义替换策略](https://github.com/houbb/sensitive-word#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9B%BF%E6%8D%A2%E7%AD%96%E7%95%A5)

**Comment by nakeiven** [comment]
> V0.2.0 已支持此特性：[自定义替换策略](https://github.com/houbb/sensitive-word#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9B%BF%E6%8D%A2%E7%AD%96%E7%95%A5)

感谢
