### ISSUE TITLE
敏感词过滤有bug

### ISSUE THREAD

**Issue by YELLOWH** [houbb/sensitive-word#14]
实现接口：IWordDeny自定义敏感词典，词典里有两个敏感词：abc 和 ab， 只能识别到abc，识别不到ab

**Comment by houbb** [comment]
会优先匹配最长的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YELLOWH ***@***.***&gt;
发送时间: 2022年1月11日 14:59
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 敏感词过滤有bug (Issue #14)





 
实现接口：IWordDeny自定义敏感词典，词典里有两个敏感词：abc 和 ab， 只能识别到abc，识别不到ab
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
