### ISSUE TITLE
特殊场景无法识别

### ISSUE THREAD

**Issue by 1714574383** [houbb/sensitive-word#16]
符号加一个英文字母无法识别到，比如：+V，+Q这种；
但是符号加两个字母就能识别了，比如：+VX，+QQ；

**Comment by houbb** [comment]
应该是 +V +Q 不在敏感词库中，支持自定义的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1714574383 ***@***.***&gt;
发送时间: 2022年2月16日 17:38
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 特殊场景无法识别 (Issue #16)





 
符号加一个英文字母无法识别到，比如：+V，+Q这种；
 但是符号加两个字母就能识别了，比如：+VX，+QQ；
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1714574383** [comment]
我是用的自定义的敏感词库的，且确定库里是存在+V，+Q的敏感词的，但还是无法检索出来

**Comment by 1714574383** [comment]
排查到问题了，大小写问题。
设置里我已忽略大小写敏感，我的敏感词库里是大写，但是初始化敏感词库的时候并没有将大写转成小写。
格式化责任链中的这两行代码将文本内容都转成小写了。
char c = txt.charAt(index);
char mappingChar = Instances.singleton(CharFormatChain.class).format(c, context);
结果是敏感词Map是大写的key，内容是小写，Map currentMap = (Map) nowMap.get(mappingChar);取不到东西。

**Comment by houbb** [comment]
这里我后续修正下实现。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1714574383 ***@***.***&gt;
发送时间: 2022年2月17日 09:21
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 特殊场景无法识别 (Issue #16)





 
排查到问题了，大小写问题。
 设置里我已忽略大小写敏感，我的敏感词库里是大写，但是初始化敏感词库的时候并没有将大写转成小写。
 格式化责任链中的这两行代码将文本内容都转成小写了。
 char c = txt.charAt(index);
 char mappingChar = Instances.singleton(CharFormatChain.class).format(c, context);
 结果是敏感词Map是大写的key，内容是小写，Map currentMap = (Map) nowMap.get(mappingChar);取不到东西。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
