### ISSUE TITLE
当文字是数字时，数字大于等于8位会被识别为敏感词

### ISSUE THREAD

**Issue by yskcx** [houbb/sensitive-word#17]
String str= "12345678"; //str是任意的8位或以上的数字

boolean contains = wordBs.contains(str);

contains 是true

**Comment by yskcx** [comment]
![image](https://user-images.githubusercontent.com/41769420/156735860-645cd140-a695-47d9-acd3-55475fc36a26.png)

**Comment by yskcx** [comment]
把除了自定义的敏感词库检测检测关了，问题解决[哭笑]

**Comment by houbb** [comment]
看下文档。有一个 numCheck 的属性可以关闭。一般8位以上数字都是联系方式之类的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ysk ***@***.***&gt;
发送时间: 2022年3月4日 17:34
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 当文字是数字时，数字大于等于8位会被识别为敏感词 (Issue #17)





 
把除了自定义的敏感词库检测检测关了，问题解决[哭笑]
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houbb** [comment]
配置说明：[配置说明](https://github.com/houbb/sensitive-word#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)
