### ISSUE TITLE
自定义敏感词不生效

### ISSUE THREAD

**Issue by bocaiJs** [houbb/sensitive-word#20]
```
SensitiveWordBs wordBs = SensitiveWordBs.newInstance()
               .wordDeny(new MyDdWordDeny())
               .init();

       final String text = "五星红旗迎风飘扬，毛主席的画像屹立在天安门前。视频，测试";
       boolean contains = wordBs.contains(text);
       if(contains){
           List<String> wordList = SensitiveWordHelper.findAll(text);
           System.out.println("wordList = " + wordList);
           System.out.println("wordList = " + wordList);
       }

@Component
public class MyDdWordDeny implements IWordDeny {

    @Override
    public List<String> deny() {
        List<String> objects = new ArrayList<>();
        objects.add("测试");
        // 数据库查询
        return objects;
    }

}

wordList = [五星红旗, 毛主席, 天安门, 视频]
```

加载了自定义的敏感词 里面只有一个『测试』没有生效

生效的还是自带的词库

请问是哪里的问题呢

**Comment by bocaiJs** [comment]
@houbb  大佬 帮忙看看呢 版本是0.2.0

**Comment by houbb** [comment]
你初始化用的 wordBs，但是方法调用使用的是通用的工具类。
你继续使用 wordBs 里面的方法才能符合预期。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bocaiJs ***@***.***&gt;
发送时间: 2022年4月7日 17:35
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 自定义敏感词不生效 (Issue #20)





 SensitiveWordBs wordBs = SensitiveWordBs.newInstance()                .wordDeny(new MyDdWordDeny())                .init();        final String text = "五星红旗迎风飘扬，毛主席的画像屹立在天安门前。视频，测试";        boolean contains = wordBs.contains(text);        if(contains){            List<String&gt; wordList = SensitiveWordHelper.findAll(text);            System.out.println("wordList = " + wordList);            System.out.println("wordList = " + wordList);        } @Component public class MyDdWordDeny implements IWordDeny {     @Override     public List<String&gt; deny() {         List<String&gt; objects = new ArrayList<&gt;();         objects.add("测试");         // 数据库查询         return objects;     } } wordList = [五星红旗, 毛主席, 天安门, 视频]  
加载了自定义的敏感词 里面只有一个『测试』没有生效
 
生效的还是自带的词库
 
请问是哪里的问题呢

**Comment by bocaiJs** [comment]
> 你初始化用的 wordBs，但是方法调用使用的是通用的工具类。 你继续使用 wordBs 里面的方法才能符合预期。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: bocaiJs ***@***.***&gt; 发送时间: 2022年4月7日 17:35 收件人: houbb/sensitive-word ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [houbb/sensitive-word] 自定义敏感词不生效 (Issue #20) SensitiveWordBs wordBs = SensitiveWordBs.newInstance() .wordDeny(new MyDdWordDeny()) .init(); final String text = "五星红旗迎风飘扬，毛主席的画像屹立在天安门前。视频，测试"; boolean contains = wordBs.contains(text); if(contains){ List<String&gt; wordList = SensitiveWordHelper.findAll(text); System.out.println("wordList = " + wordList); System.out.println("wordList = " + wordList); } @component public class MyDdWordDeny implements IWordDeny { @OverRide public List<String&gt; deny() { List<String&gt; objects = new ArrayList<&gt;(); objects.add("测试"); // 数据库查询 return objects; } } wordList = [五星红旗, 毛主席, 天安门, 视频] 加载了自定义的敏感词 里面只有一个『测试』没有生效 生效的还是自带的词库 请问是哪里的问题呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢大佬。问题解决了， 我太笨了
