### ISSUE TITLE
为啥网址都是敏感词呢 怎么忽略网址的校验呢

### ISSUE THREAD

**Issue by bocaiJs** [houbb/sensitive-word#21]

**Comment by houbb** [comment]
可以读一下首页文档，应该有说明。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bocaiJs ***@***.***&gt;
发送时间: 2022年7月26日 17:23
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 为啥网址都是敏感词呢 怎么忽略网址的校验呢 (Issue #21)

**Comment by bocaiJs** [comment]
谢谢老哥 找到了@houbb
