### ISSUE TITLE
敏感词包含重复字符的，无法识别

### ISSUE THREAD

**Issue by whh1009** [houbb/sensitive-word#23]
自定义敏感词库：
```
tmd
nnd
```
`tmd`被识别为敏感词
`nnd`却不行

有人碰到这样的情况没？

**Comment by whh1009** [comment]
我好像找到问题了，只要有连续的重复的字符都会有问题！
举例：
```
法网恢恢
nnd
不良少少日记
杨元元
毛爷爷复活
高莺莺
先烈的电电
咪咪
```

哇哦！

**Comment by houbb** [comment]
有一个重复检测的开关，可以选择关闭。或者把重复词去掉重复的部门都行，


后面针对这一点我准备改进一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whh ***@***.***&gt;
发送时间: 2022年8月9日 15:08
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 自定义的敏感词，有些能识别，有些不能识别 (Issue #23)





 
我好像找到问题了，只要有连续的重复的字符都会有问题！
 举例：
 法网恢恢 nnd 不良少少日记 杨元元 毛爷爷复活 高莺莺 先烈的电电 咪咪  
哇哦！

**Comment by houbb** [comment]
解决方式：

方案1：有一个重复检测的开关，可以选择关闭。[配置项说明](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

方案2：包吃重复检查开关不变，把配置的单词中的重复信息去掉。
