### ISSUE TITLE
敏感词为包含关系时大部分会默认识别长的,但有些会识别短的

### ISSUE THREAD

**Issue by wang-droid** [houbb/sensitive-word#24]
具体举例自定义敏感词O 和 O̷  前者是包含后者的,但识别的时候却识别出来后者  

具体表现为:首先上面俩个敏感词的替换策略都是想替换成0,我输入个王O来进行替换的时候会输出王O 就是因为会先识别 O̷ 这个敏感词替换为o然后在拼接后面的

**Comment by wang-droid** [comment]
> 具体举例自定义敏感词O 和 O̷ 前者是包含后者的,但识别的时候却识别出来后者
> 
> 具体表现为:首先上面俩个敏感词的替换策略都是想替换成0,我输入个王O来进行替换的时候会输出王O 就是因为会先识别 O̷ 这个敏感词替换为o然后在拼接后面的

上面的俩个敏感词显示有问题,补充下是 Ŏ̷̢̡̩̯̰̪̘͈̦͘ 和 O̷  然后返回Ŏ̢̡̩̯̰̪̘͈̦͘

**Comment by wang-droid** [comment]
@houbb  大佬,有时间辛苦看看

**Comment by houbb** [comment]
你可以先 debug 下源码，我最近比较忙。后面有时间我看下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangmw ***@***.***&gt;
发送时间: 2022年9月17日 20:36
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 敏感词为包含关系时大部分会默认识别长的,但有些会识别短的 (Issue #24)





 
具体举例自定义敏感词 O 和 O̷  前者是包含后者的,但识别的时候却识别出来后者
 
具体表现为:首先上面俩个敏感词的替换策略都是0,我输入个王O来进行替换的时候会输出王O 就是因为会先识别 O̷ 这个敏感词替换为o然后在拼接后面的

**Comment by wang-droid** [comment]
大佬 有结论了吗

**Comment by houbb** [comment]
新版本应该已经修正了，可以确认下。
