### ISSUE TITLE
enableNumCheck支持指定连续数字位

### ISSUE THREAD

**Issue by SimonHu1993** [houbb/sensitive-word#26]
默认是8，建议自定义长度，产品可能就要求9位以上- -

**Comment by houbb** [comment]
可以的 我有时间见一下这个特性

**Comment by houbb** [comment]
v2.1.0 已支持。

参见：[数字检测特性](https://github.com/houbb/sensitive-word#%E8%BF%9E%E7%BB%AD%E6%95%B0%E5%AD%97%E6%A3%80%E6%B5%8B)
