### ISSUE TITLE
请问自定义deny词库有什么要求吗？

### ISSUE THREAD

**Issue by grover572** [houbb/sensitive-word#30]
请问自定义deny词库有什么要求吗？类似关键词长度之类的？因为我添加了一个“代课”的关键字没生效，然后用WordDenys.system()是生效的

**Comment by houbb** [comment]
没啥要求，可以看下例子。


大概率是用错了，比如指定了配置，要用指定后的引导类方法。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Saturn ***@***.***&gt;
发送时间: 2023年4月29日 17:14
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 请问自定义deny词库有什么要求吗？ (Issue #30)





 
请问自定义deny词库有什么要求吗？类似关键词长度之类的？因为我添加了一个“代课”的关键字没生效，然后用WordDenys.system()是生效的

**Comment by grover572** [comment]
找到原因了～
我是用Spring注入的SensitiveWordBs，但是使用的时候用了SensitiveWordHelper，导致又在SensitiveWordHelper中new了WORD_BS

感谢houbb
