### ISSUE TITLE
敏感词关于数字检测bug

### ISSUE THREAD

**Issue by cyljx9999** [houbb/sensitive-word#32]
当设置了numCheckLen之后，ignoreNumStyle设置为false之后依旧会进行检测位数进行替换，不应该ignoreNumStyle设置为false不进行数字检测嘛

**Comment by houbb** [comment]
看下文档。


你设置的是忽略数字的样式，启用功能与否用 enableXXX。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 清梦 ***@***.***&gt;
发送时间: 2023年5月12日 20:56
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 敏感词关于数字检测bug (Issue #32)





 
当设置了numCheckLen之后，ignoreNumStyle设置为false之后依旧会进行检测位数进行替换，不应该ignoreNumStyle设置为false不进行数字检测嘛

**Comment by cyljx9999** [comment]
0.0,我的问题
