### ISSUE TITLE
敏感词是不是要求太严格了 

### ISSUE THREAD

**Issue by 327078466** [houbb/sensitive-word#37]
你在干嘛 中的干算敏感词？

**Comment by houbb** [comment]
支持白名单。







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 327078466 ***@***.***&gt;
发送时间: 2023年11月15日 11:22
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 敏感词是不是要求太严格了  (Issue #37)





 
你在干嘛 中的干算敏感词？

**Comment by houbb** [comment]
v0.9.0 已修正，移除了单个字。

**Comment by 327078466** [comment]
0.9.0 maven仓库中还搜不到
