### ISSUE TITLE
可以只过滤广告营销的内容吗？

### ISSUE THREAD

**Issue by changfeng2021** [houbb/sensitive-word#39]
政治相关的内容不过滤

**Comment by houbb** [comment]
缺少了一个脏词标签的维护，目前精力有限，没做这个。

**Comment by houbb** [comment]
接口能力已经提供了。

> [敏感词标签](https://github.com/houbb/sensitive-word/blob/master/README.md#%E6%95%8F%E6%84%9F%E8%AF%8D%E6%A0%87%E7%AD%BE)
