### ISSUE TITLE
麻烦支持下关键字动态加载

### ISSUE THREAD

**Issue by aboboo520** [houbb/sensitive-word#4]
支持关键词支持外部传入，比如从数据库加载，目前自定义的两个文件只能先写死，无法动态加载

**Comment by houbb** [comment]
v0.0.13 已经支持，感谢建议。

[关键字动态加载](https://github.com/houbb/sensitive-word#%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD)
