### ISSUE TITLE
提个遇到的问题

### ISSUE THREAD

**Issue by hq112415** [houbb/sensitive-word#40]
代码为：
        final List<String> words = Lists.newArrayList("fuck", "cao", "shit", "shift");

        SensitiveWordBs holder = SensitiveWordBs.newInstance()
                .enableNumCheck(false)
                .wordDeny(() -> words)
                .init();

        String word = "*OW,awv 10720hj\uD83D\uDC42YRLH\uD83D\uDE4Cl.L #N, E in cR,aQlgQ. 9k.a+47 gfj172.J59 ptjaUSERa ]#075'8\uD83D\uDE46asYKO.QRW.XVMYV 713e5*foovco6tm9# kP G.SLKPR 'GA14998b\\nGjiw a7jz l,aaeeg\\nphd  jgt y\\n@zamnko ";
        System.out.println(holder.findAll(word));
        
命中:
[asYKO.QRW.XVMYV, G.SLKPR]

**Comment by houbb** [comment]
应该是命中了网址之类的，可以本地 debug 试一下。网址的检测可以关闭
