### ISSUE TITLE
能否同时判别多个词存在的情况

### ISSUE THREAD

**Issue by shanty1** [houbb/sensitive-word#42]
能判别多个词同时存在的情况吗， 比如“死人   刺杀”， 同时存在才算文本敏感。

**Comment by houbb** [comment]
那应该把这个词作为一个自定义敏感词。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Amor ***@***.***&gt;
发送时间: 2023年12月25日 15:02
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 能否同时判别多个词存在的情况 (Issue #42)





 
能判别多个词同时存在的情况吗， 比如“死人   刺杀”， 同时存在才算文本敏感。

**Comment by houbb** [comment]
或者自己添加策略，获取所有敏感词，然后判断是否同时存在你说的多个。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Amor ***@***.***&gt;
发送时间: 2023年12月25日 15:02
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 能否同时判别多个词存在的情况 (Issue #42)





 
能判别多个词同时存在的情况吗， 比如“死人   刺杀”， 同时存在才算文本敏感。
