### ISSUE TITLE
忽略字符问题

### ISSUE THREAD

**Issue by liutao-lx** [houbb/sensitive-word#48]
我在找到[傻@帽，狗+东西]这个集合后，我没有找到如何处理这个集合的思路，多谢

**Comment by houbb** [comment]
你把中间的特殊符号，当作忽略字符就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liutao-lx ***@***.***&gt;
发送时间: 2024年3月5日 16:48
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 忽略字符问题 (Issue #48)





 
我在找到[傻@帽，狗+东西]这个集合后，我没有找到如何处理这个集合的思路，多谢

**Comment by chuntungho** [comment]
标签获取存在问题，如：傻@帽，应该是获取“傻帽”对应的标签
