### ISSUE TITLE
其他包,里面存在dict.txt文件，sensitive-word会读取其他包中的dict.txt

### ISSUE THREAD

**Issue by pechmiao** [houbb/sensitive-word#54]
目前发现alink_core_flink-1.11_2.11这个包里面也有个dict.txt文件，pom里面如果先引用alink_core_flink-1.11_2.11，然后再引用sensitive-word，初始化的时候List<String> results = StreamUtil.readAllLines("/dict_word.txt");这个方法就会读alink_core_flink-1.11_2.11里面的文件

**Comment by houbb** [comment]
v0.15.0 已优化。 dict.txt=>sensitive_word_dict.txt
