### ISSUE TITLE
[Bug]一长串代码会被检测到含有敏感词

### ISSUE THREAD

**Issue by eddsi** [houbb/sensitive-word#56]
if !hit {
	CollectQuota(conn.GetCtx(), user, buffer, plan, err)
}

if buffer.IsEmpty() {
	conn.Send(globals.ChatSegmentResponse{
		Message: defaultMessage,
		End:     true,
	})
	return defaultMessage
}

conn.Send(globals.ChatSegmentResponse{
	End:   true,
	Quota: buffer.GetQuota(),
	Plan:  plan,
})

return buffer.ReadWithDefault(defaultMessage)
上述go代码会被检测出敏感词，但是我仔细检查了一下，并不包含dict_en中的英文。

**Comment by houbb** [comment]
默认被识别为 url 了。

v0.16.2 默认关闭了 url 检测，以前的版本可以配置指定。
