### ISSUE TITLE
建议可以分别开关 涉黄、涉政、营销等不同类型的关键字

### ISSUE THREAD

**Issue by qiaoshouqing** [houbb/sensitive-word#57]
比如我其实不想过滤掉营销类型的，用起来就会很烦。

**Comment by houbb** [comment]
v0.24.0 版本开始内置支持，参考 [敏感词标签](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E6%95%8F%E6%84%9F%E8%AF%8D%E6%A0%87%E7%AD%BE)
