### ISSUE TITLE
[功能建议] 敏感词根据功能场景进行区分。

### ISSUE THREAD

**Issue by 1428260762** [houbb/sensitive-word#60]
最终希望可以：在指定场景，只有包含指定Tag的敏感词生效。

现在的敏感词替换方法入参都是{Text文本}，将入参扩展为{Text文本}，{TagList适用的标签列表}。
进行匹配/替换/查询时只处理包含指定Tag的敏感词。

**Comment by houbb** [comment]
v0.24.0 版本开始内置支持，参考 [敏感词标签](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E6%95%8F%E6%84%9F%E8%AF%8D%E6%A0%87%E7%AD%BE)
