### ISSUE TITLE
期望能够移除"女装"等一系列比较正常的词语

### ISSUE THREAD

**Issue by OPGithub** [houbb/sensitive-word#61]
在做商城系统敏感词过滤的时候，发现女装也是敏感词，导致发布的商品异常

**Comment by OPGithub** [comment]
另外还有装修、妹妹、他爸爸这种单独使用并不算敏感的敏感词

希望这种过滤：他妈妈不是敏感词，也就是说他妈妈加入了白名单之后，里面期望显示他妈妈，而不是**妈

**Comment by OPGithub** [comment]
> 嗯 因为敏感词的有一部分是营销 所以和商城类目会冲突。
> 
> 第二个问题可以把【他妈】这种也加入白名单，因为会匹配最短的。

可不可以优先匹配白名单的，比如他妈妈存在白名单，就不用匹配这个白名单里面的敏感词【他妈】了

**Comment by houbb** [comment]
v0.16.2 移除了你提到的几个常用词。
