### ISSUE TITLE
为什么默认初始化一个SensitiveWordBs对象，要占用这么高内存

### ISSUE THREAD

**Issue by lxw6933** [houbb/sensitive-word#62]
初始化空对象
打印对象大小：
long objectSize = ObjectSizeCalculator.getObjectSize(sensitiveWordBs);
log.info("sensitiveWordBs size：【{}】byte", objectSize);
输出：
sensitiveWordBs size：【35043720】byte

**Comment by houbb** [comment]
默认加载了内置字典，可以配置去掉。
