### ISSUE TITLE
[装修, 大陆]这两个字为什么也过不了呢

### ISSUE THREAD

**Issue by lxd7788** [houbb/sensitive-word#66]
我这里的内容大概是大陆阳光这个地方，家具装修相关的数据。。。。
大陆还可以勉强理解，装修是为什么

**Comment by houbb** [comment]
装修属于广告🪧 可以自己定义白名单



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lxd7788 ***@***.***&gt;
发送时间: 2024年7月12日 11:18
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] [装修, 大陆]这两个字为什么也过不了呢 (Issue #66)





 
我这里的内容大概是大陆阳光这个地方，家具装修相关的数据。。。。
 大陆还可以勉强理解，装修是为什么
