### ISSUE TITLE
没在库里的乱打的数字也会触发敏感词

### ISSUE THREAD

**Issue by manongqiyin** [houbb/sensitive-word#67]
在测试的时候发现 CensoredWordConfig.getSensitiveWordBs().findAll(article.getText())
其中article.getText()中包含类似于1221211212、1223222111这样乱打的数字也会触发

且该类数字并不在库里面

**Comment by houbb** [comment]
数字是否检测可以关闭



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: manongqiyin ***@***.***&gt;
发送时间: 2024年7月12日 17:30
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 没在库里的乱打的数字也会触发敏感词 (Issue #67)





 
在测试的时候发现 CensoredWordConfig.getSensitiveWordBs().findAll(article.getText())
 其中article.getText()中包含类似于1221211212、1223222111这样乱打的数字也会触发
 
且该类数字并不在库里面
