### ISSUE TITLE
html 标签敏感词替换，右标签 > 被误脱敏

### ISSUE THREAD

**Issue by hss-oss** [houbb/sensitive-word#68]
![image](https://github.com/user-attachments/assets/2a6d3a93-b547-4164-a783-0a6d62831379)
![image](https://github.com/user-attachments/assets/549ad14e-720f-45c4-984b-3662d7289749)
charIgnore设置为SensitiveWordCharIgnores.specialChars()，对于html文本，会向左多识别一位字符，比如：
输入 “<p>傻逼</p>”，返回"<p***</p>"， 有个右标签 > 被替换掉了
![image](https://github.com/user-attachments/assets/ab6cf467-04ee-41bf-93d8-e8d539822d4d)

**Comment by houbb** [comment]
感谢提醒 v0.19.2 版本已修正。
