### ISSUE TITLE
Bean创建失败，报错Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null

### ISSUE THREAD

**Issue by NBHZW** [houbb/sensitive-word#72]
这是报错
![image](https://github.com/user-attachments/assets/d9d7afc3-d7e5-4ff1-a73e-a241445bd067)
这是config配置类
@Configuration
public class SpringSensitiveWordConfig {
    @Resource
    private WordDeny wordDeny;
    /**初始化引导类
     * @return 初始化引导类
     * @since 1.0.0
     * */
    @Bean
    public SensitiveWordBs sensitiveWordBs() {
        SensitiveWordBs sensitiveWordBs = SensitiveWordBs.newInstance()
                .wordDeny(WordDenys.chains(WordDenys.defaults(),wordDeny))
                .enableNumCheck(true)
                .enableEmailCheck(true)
                .enableUrlCheck(true)
                .init();
        return sensitiveWordBs;
    }
}
![image](https://github.com/user-attachments/assets/b63629d7-b280-4d23-9d10-29b07343c036)
这是自定义的铭感词类
@Service
public class WordDeny implements IWordDeny {
    @Resource
    private SensitiveWordMapper sensitiveWordMapper;
    @Override
    public List<String> deny() {
        LambdaQueryWrapper<SensitiveWord> queryWrapper=new LambdaQueryWrapper<>();
        queryWrapper.eq(SensitiveWord::getStatus,0);
        List<SensitiveWord> sensitiveWords = sensitiveWordMapper.selectList(queryWrapper);
        if(CollectionUtil.isNotEmpty(sensitiveWords)){
            List<String> list = sensitiveWords.stream().map(SensitiveWord::getSensitiveWord).toList();
            return list;
        }else{
            return null;
        }
    }
}
![image](https://github.com/user-attachments/assets/18fe4ab0-a280-4f0b-9392-92f78ecc420d)

**Comment by hangker1997** [comment]
return null 改一下  改成  rerurn new ArrayList<>();

**Comment by houbb** [comment]
v0.18.1 已兼容 null 场景。
