### ISSUE TITLE
咨询下白名单问题

### ISSUE THREAD

**Issue by luolei100** [houbb/sensitive-word#76]
![image](https://github.com/user-attachments/assets/6fcdff42-079c-4fbd-8fd2-db3917d5e2b3)

这种情况如何让白名单“三黄片”生效。
```

SensitiveWordBs init = SensitiveWordBs.newInstance()
                .wordAllow(WordAllows.chains(WordAllows.defaults(),
                        () -> Lists.newArrayList("三黄片")))
                .wordDeny(WordDenys.chains(WordDenys.defaults()))
                .ignoreRepeat(true)
                .ignoreChineseStyle(true).init();
        init.addWord();

        System.out.println(init.replace("三黄片"));
```
com.github.houbb.sensitive.word.bs.SensitiveWordBs#addWord(java.util.Collection<java.lang.String>)

然后如何动态添加白名单词组， 或者我控制台新增的白名单词组如何生效？

**Comment by houbb** [comment]
优先匹配到了【黄片】，目前的白名单设计的只影响到了最初的字典初始化，感觉是设计缺陷。我后续考虑优化一下。

**Comment by houbb** [comment]
v0.21.0 已修正此问题，白名单较长，包含了黑名单的问题。
