### ISSUE TITLE
数字类的敏感词完全匹配

### ISSUE THREAD

**Issue by Alice-smail** [houbb/sensitive-word#77]
使用的是contains方法，text是trade deficit totaled 695 billion yen, or $4.9 billion，通过findAll获取到敏感词是69。
期望的应该是没有匹配到敏感词，像英文全词匹配一样，只有敏感词库中包含完整的69才会返回为true，否则应该返回为false。
这种情况可以优化吗？或者哪个同学已经实现了，可以聊一下实现方案啊，谢谢！

**Comment by houbb** [comment]
v0.20.0 已支持。

**Comment by Alice-smail** [comment]
我把白名单的69去掉，自定义的deny中添加69，版本升级到V0.20.0，配置项添加了wordResultCondition(WordResultConditions.englishWordNumMatch())，测试了一下trade deficit totaled 695 billion yen, or $4.9 billion，返回的是true，findAll获取到的还是69，没有生效呢。
使用白名单，添加69和配置项，同一个文本，返回的是false

**Comment by Alice-smail** [comment]
搞定了，只需要.wordResultCondition(WordResultConditions.englishWordNumMatch())配置就好，英文的全词匹配就不需要了，感谢老马啸西风！！！
