### ISSUE TITLE
字库问题

### ISSUE THREAD

**Issue by robben009** [houbb/sensitive-word#79]
这个敏感词的词库是内置的吗？可否外挂文本来扩充词库

**Comment by houbb** [comment]
支持的，敏感词实现用户可以自定义。

参考：[用户自定义词库实现](https://github.com/houbb/sensitive-word#%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8)

**Comment by robben009** [comment]
> 支持的，敏感词实现用户可以自定义。
> 
> 参考：[用户自定义词库实现](https://github.com/houbb/sensitive-word#%E9%85%8D%E7%BD%AE%E4%BD%BF%E7%94%A8)

ok,之前没细看，感谢大佬
