### ISSUE TITLE
大佬，能不能把 ignoreRepeat暴露出来。

### ISSUE THREAD

**Issue by lhholylight** [houbb/sensitive-word#8]

**Comment by houbb** [comment]
可以的，内部的配置都准备打开的，这周我把这个特新放开一下。

**Comment by houbb** [comment]
v0.0.14 已经支持。

> 参考 [特新配置](https://github.com/houbb/sensitive-word#%E7%89%B9%E6%80%A7%E9%85%8D%E7%BD%AE)
