### ISSUE TITLE
使用过程中发现对包含汉字零~九的敏感词无法过滤

### ISSUE THREAD

**Issue by dinghal** [houbb/sensitive-word#84]
例如，敏感词“下三滥”。通过
this.sensitiveWordBs = SensitiveWordBs.newInstance().wordAllow(WordAllows.empty()).wordDeny(WordDenys.empty()).init();
this.sensitiveWordBs.addWord("下三滥");
方式添加。
sensitiveWordBs.findFirst("花豹用下三滥招式对付疣猪，没想到疣猪居然也有绝招")的方式使用，返回null

**Comment by houbb** [comment]
因为[数字写法的忽略问题](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E5%BF%BD%E7%95%A5%E6%95%B0%E5%AD%97%E7%9A%84%E5%86%99%E6%B3%95)：

```java
final String text = "这个是我的微信：9⓿二肆⁹₈③⑸⒋➃㈤㊄";

List<String> wordList = SensitiveWordBs.newInstance().enableNumCheck(true).init().findAll(text);
Assert.assertEquals("[9⓿二肆⁹₈③⑸⒋➃㈤㊄]", wordList.toString());
```

数字【三】在启用时，词库中应该默认加工成了【3】。后续考虑改进一下词库的初始化

**Comment by mole422** [comment]
在处理敏感词过滤时，确实需要考虑到数字的不同表示方式，包括阿拉伯数字、中文数字、罗马数字等，以及它们的变体（如全角数字、特殊字符表示的数字等）。在你提到的情况中，敏感词“下三滥”中的“三”可能会被数字“3”替换，导致敏感词匹配失败。为了解决这个问题，我觉得可以采取以下几种方法：
1. 扩展词库：
   在初始化敏感词库时，将所有可能的数字变体都加入到词库中。例如，除了“三”之外，还可以添加“③”、“3”等变体。

   ```java
   this.sensitiveWordBs = SensitiveWordBs.newInstance().wordAllow(WordAllows.empty()).wordDeny(WordDenys.empty()).init();
   this.sensitiveWordBs.addWord("下三滥");
   this.sensitiveWordBs.addWord("下③滥"); // 添加数字变体
   this.sensitiveWordBs.addWord("下3滥"); // 添加阿拉伯数字变体
   ```

2. **数字识别与替换**：
   在匹配敏感词之前，对文本进行预处理，将所有数字变体替换为标准形式（如阿拉伯数字），然后再进行敏感词匹配。

   ```java
   String text = "花豹用下三滥招式对付疣猪，没想到疣猪居然也有绝招";
   text = replaceNumericVariants(text); // 将数字变体替换为标准形式
   String result = sensitiveWordBs.findFirst(text);
   ```

   其中`replaceNumericVariants`是一个自定义的方法，用于替换文本中的数字变体。

3. **改进 DFA 算法**：
   在 DFA（确定性有限自动机）算法中，可以在状态转移时考虑到数字的不同表示。例如，为每个状态添加一个额外的映射，用于处理数字变体。

4. **正则表达式**：
   使用正则表达式来匹配敏感词，正则表达式可以灵活地定义数字的变体。

   ```java
   Pattern pattern = Pattern.compile("下(三|③|3)滥", Pattern.CASE_INSENSITIVE);
   Matcher matcher = pattern.matcher(text);
   if (matcher.find()) {
       // 找到敏感词
   }
   ```

**Comment by mole422** [comment]
出现这个情况主要原因是当自定义添加敏感词带有中文数字的时候词库虽然有了对应的敏感词但是每次处理语句匹配敏感词的时候都会把中文数字转换成阿拉伯数字进行匹配，导致永远匹配不到词库那个敏感词，如词库中是“下三滥”，处理语句时候识别的是“下3滥”。我认为可以在添加敏感词时，先将敏感词按原始格式添加到库中，再将汉字数字转换为阿拉伯数字的形式，并添加到库中。这样可以匹配到两种格式的敏感词。由于添加时已进行了多格式处理，所以检测时能够自动匹配到“下三滥”或“下3滥”格式。

**Comment by houbb** [comment]
v0.22.0 版本已修正此问题。
问题原因：单独的黑名名单未做统一的格式化处理，导致格式未匹配。

测试用例如下：

```java
  public void bug84IgnoreNumberStyleTrueTest() {
        // 例如，敏感词“下三滥”。通过
        SensitiveWordBs sensitiveWordBs = SensitiveWordBs.newInstance()
                .wordAllow(WordAllows.empty())
                .wordDeny(WordDenys.empty())
                // 因为这里默认是 true
                .ignoreNumStyle(true)
                .init();
        sensitiveWordBs.addWord("下三滥");
        String result = sensitiveWordBs.findFirst("花豹用下三滥招式对付疣猪，没想到疣猪居然也有绝招");
        Assert.assertEquals("下三滥", result);

        String result2 = sensitiveWordBs.findFirst("花豹用下3滥招式对付疣猪，没想到疣猪居然也有绝招");
        Assert.assertEquals("下3滥", result2);

        // 移除
        sensitiveWordBs.removeWord("下三滥");
        String result3 = sensitiveWordBs.findFirst("花豹用下三滥招式对付疣猪，没想到疣猪居然也有绝招");
        Assert.assertNull(result3);

        String result4 = sensitiveWordBs.findFirst("花豹用下3滥招式对付疣猪，没想到疣猪居然也有绝招");
        Assert.assertNull(result4);
    }
```
