### ISSUE TITLE
匹配问题

### ISSUE THREAD

**Issue by czyeclipse** [houbb/sensitive-word#85]
[sensitive_word_dict.txt](https://github.com/user-attachments/files/17676773/sensitive_word_dict.txt)
请问一下大佬：使用这个词库为啥会匹配出：64这个词呢？词库中并没有单独的64啊

**Comment by houbb** [comment]
因为[数字写法的忽略问题](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E5%BF%BD%E7%95%A5%E6%95%B0%E5%AD%97%E7%9A%84%E5%86%99%E6%B3%95)：

```java
final String text = "这个是我的微信：9⓿二肆⁹₈③⑸⒋➃㈤㊄";

List<String> wordList = SensitiveWordBs.newInstance().enableNumCheck(true).init().findAll(text);
Assert.assertEquals("[9⓿二肆⁹₈③⑸⒋➃㈤㊄]", wordList.toString());
```

系统词库中应该是有【六四】或者【64】的，可以看一下
