### ISSUE TITLE
如何实现匹配多个敏感词

### ISSUE THREAD

**Issue by WayneLee5991** [houbb/sensitive-word#91]
我自定义了多个敏感词 a、b、c、d等等，只有这个文本同时命中了a和b才可以，只命中a或者只命中b都不算，这种怎么实现呢？

**Comment by houbb** [comment]
得到敏感词后，自己程序再判断一次。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WayneLee ***@***.***&gt;
发送时间: 2024年12月9日 17:43
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 如何实现匹配多个敏感词 (Issue #91)





 
我自定义了多个敏感词 a、b、c、d等等，只有这个文本同时命中了a和b才可以，只命中a或者只命中b都不算，这种怎么实现呢？
