### ISSUE TITLE
自带的敏感词库能加上标签吗？

### ISSUE THREAD

**Issue by eschervr-dev** [houbb/sensitive-word#92]
自带的敏感词库能加上标签吗？

**Comment by houbb** [comment]
支持自定义标签 文档有写



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: eschervr-dev ***@***.***&gt;
发送时间: 2024年12月16日 10:35
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] 自带的敏感词库能加上标签吗？ (Issue #92)





 
自带的敏感词库能加上标签吗？

**Comment by houbb** [comment]
v0.24.0 版本开始内置支持，参考 [敏感词标签](https://github.com/houbb/sensitive-word?tab=readme-ov-file#%E6%95%8F%E6%84%9F%E8%AF%8D%E6%A0%87%E7%AD%BE)
