### ISSUE TITLE
sensitive-word可以用于商业目的吗？

### ISSUE THREAD

**Issue by magaojie** [houbb/sensitive-word#94]
您好，请问我可以在商业软件中引用sensitive-word.jar包吗？会侵权吗？

**Comment by magaojie** [comment]
我用的sensitive-word版本是 0.23.0

**Comment by houbb** [comment]
不会 Apache 2.0&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: magaojie ***@***.***&gt;
发送时间: 2024年12月18日 18:17
收件人: houbb/sensitive-word ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/sensitive-word] sensitive-word可以用于商业目的吗？ (Issue #94)





 
您好，请问我可以在商业软件中引用sensitive-word.jar包吗？会侵权吗？

**Comment by magaojie** [comment]
> 不会 Apache 2.0&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: magaojie ***@***.***&gt; 发送时间: 2024年12月18日 18:17 收件人: houbb/sensitive-word ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [houbb/sensitive-word] sensitive-word可以用于商业目的吗？ (Issue #94) 您好，请问我可以在商业软件中引用sensitive-word.jar包吗？会侵权吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

收到,感谢
